apiVersion: apps/v1beta1 
kind: Deployment 
metadata: 
  name: [name]-deployment
  namespace: [namespace]
  labels: 
    app: [name]
spec: 
  replicas: 1
  minReadySeconds: 10 
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1 
      maxUnavailable: 0 
  selector: 
    matchLabels: 
      app: [name] 
  template: 
    metadata:  
      labels: 
        app: [name] 
    spec: 
      containers: 
      - name: [name]
        image: [].cloudzcp.io/[]/[image_name]:1
        ports:  
        - containerPort: 3005 
        imagePullPolicy: Always